on:
  push:
    branches:
      - main
      - MR_Integration
name: HosPice Deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build web
      - uses: actions/upload-artifact@master
        with:
          name: web
          path: build/web
      - name: Deploy HosPice Hub
steps:
      - name: Install SSH Key
        uses: action/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 
          - name: Adding Known Hosts
            run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/web
